### ISSUE TITLE
metavars not being enforce throughout entire rule

### ISSUE THREAD

**Issue by DrewDennison** [returntocorp/sgrep#230] opened 2020-03-03 03:48 UTC
https://sgrep.live/rxW

real-world impact / dup of #176 cc @nbrahms 

`python.smells.list-pop-while-iterate` matches

```python 
assignment = {}
with open(args.ordering) as f:
    for line in f.readlines():
        array = line.lstrip().rstrip().split("\t")
        if len(array) == 2:
            name = array[0]
            trait = array[1]
            if name not in assignment:
                assignment[name] = [trait]
            else:
                assignment[name].append(trait)
```

Found while running `--config=r2c-develop` over https://github.com/nextstrain/ncov

**Comment by ievans** [comment] 2020-03-03 03:53
Duplicate of #176

**Closed by ievans** 2020-03-03 03:53 UTC
Labels: bug, sgrep-lint
